name: Build Android APK + AAB
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Unzip project
        run: unzip -q whole_hymn_folder.zip -d android-project

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x android-project/gradlew

      - name: Build Debug APK
        run: cd android-project &&./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android-project/app/build/outputs/apk/debug/*.apk

      - name: Build AAB
        run: cd android-project &&./gradlew bundleRelease

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release.aab
          path: android-project/app/build/outputs/bundle/release/*.aab
